driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
url=jdbc:sqlserver://;databaseName=jdbc;trustServerCertificate=true;
username=root
password=1247

# 初始化連線數：一啟動就先開好幾條
initialSize=5
# 最大連線數：池子最多同時有幾條
maxActive=10
# 最大等待時間(毫秒)：借不到連線時最多等多久，超過就丟例外
maxWait=3000